//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenterWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CITAS()
        {
            this.FOTOS = new HashSet<FOTOS>();
            this.MENSAJES = new HashSet<MENSAJES>();
            this.SERVICIOS = new HashSet<SERVICIOS>();
        }
    
        public decimal ID_CITA { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public string ESTADO_CITA { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string MOTIVO_CITA { get; set; }
        public decimal ID_PERSONA_VEHICULO { get; set; }
    
        public virtual PERSONA_VEHICULO PERSONA_VEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTOS> FOTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAJES> MENSAJES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
    }
}
