//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCenterWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOTOS
    {
        public decimal ID_FOTO { get; set; }
        public string URL_FOTO { get; set; }
        public decimal ID_CITA { get; set; }
    
        public virtual CITAS CITAS { get; set; }
    }
}
