create database carcenter;
use carcenter;

CREATE TABLE DOMINIOS(
TIPO_DOMINIO	VARCHAR(50)		NOT NULL,
ID_DOMINIO		VARCHAR(10)		NOT NULL,
VLR_DOMINIO		VARCHAR(50)		NOT NULL,
PRIMARY KEY(TIPO_DOMINIO, ID_DOMINIO));

CREATE TABLE FACTURAS(
NUM_FACTURA		NUMERIC(10)		PRIMARY KEY		IDENTITY(1,1),
FECHA_FACTURA	DATETIME		NOT NULL);

CREATE TABLE PERSONAS(
IDENTIFICACION		NUMERIC(15)		PRIMARY KEY,
NOMBRES				VARCHAR(100)	NOT NULL,
TELEFONO			NUMERIC(10)		NOT NULL,
DIRECCION			VARCHAR(100),
CORREO				VARCHAR(100)	NOT NULl,
ESPECIALIDAD		VARCHAR(10),
TIPO_PERSONA		VARCHAR(10),
CONTRASENA			VARCHAR(12)		NOT NULL,
ESTADO_PERSONA		VARCHAR(10)		NOT NULL,
CONSTRAINT UK_Correo UNIQUE(CORREO));

CREATE TABLE VEHICULOS(
PLACA			VARCHAR(6)		PRIMARY KEY,
MARCA			VARCHAR(10)		NOT NULL,
MODELO			NUMERIC(4)		NOT NULL,
COLOR			VARCHAR(10)		NOT NULL,
TIPO_VEHICULO	VARCHAR(10)		NOT NULL);

CREATE TABLE PERSONA_VEHICULO(
ID_PERSONA_VEHICULO			NUMERIC(5)		PRIMARY KEY		IDENTITY(1,1),
PLACA						VARCHAR(6)		NOT NULL,
IDENTIFICACION				NUMERIC(15)		NOT NULL,
ESTADO_PROP					VARCHAR(10)		NOT NULL,
CONSTRAINT FK_PER_VEH_VEH	FOREIGN KEY(PLACA) REFERENCES VEHICULOS (PLACA),
CONSTRAINT FK_PER_VEH_PER	FOREIGN KEY(IDENTIFICACION) REFERENCES PERSONAS (IDENTIFICACION),
CONSTRAINT UK_PersonaVeh UNIQUE(PLACA, IDENTIFICACION));

CREATE TABLE CITAS(
ID_CITA				NUMERIC(5)		PRIMARY KEY		IDENTITY(1,1),
FECHA_SOLICITUD		DATETIME		NOT NULL,
ESTADO_CITA			VARCHAR(10)		NOT NULL,
FECHA_CIERRE		DATETIME,
DIAGNOSTICO			VARCHAR(300),
MOTIVO_CITA			VARCHAR(300)	NOT NULL,
ID_PERSONA_VEHICULO	NUMERIC(5)		NOT NULL,
CONSTRAINT FK_CITAS_PER_VEH FOREIGN KEY (ID_PERSONA_VEHICULO) REFERENCES PERSONA_VEHICULO (ID_PERSONA_VEHICULO));

CREATE TABLE SERVICIOS(
ID_SERVICIO		NUMERIC(5)		PRIMARY KEY		IDENTITY(1,1),
DESC_SERVICIO	VARCHAR(300)	NOT NULL,
TIPO_SERVICIO	VARCHAR(10)		NOT NULL,
TIEMPO_ESTIMADO	NUMERIC(3,1)	NOT NULL,
ESTADO_SERVICIO	VARCHAR(10)		NOT NULL,
VALOR_SERVICIO	NUMERIC(6)		NOT NULL,
FECHA_SERVICIO	DATETIME		NOT NULL,
NUM_FACTURA		NUMERIC(10)		NOT NULL,
ID_CITA			NUMERIC(5)		NOT NULL,
CONSTRAINT FK_SERVICIO_FACT FOREIGN KEY(NUM_FACTURA) REFERENCES FACTURAS (NUM_FACTURA),
CONSTRAINT FK_SERVICIO_CITA FOREIGN KEY(ID_CITA) REFERENCES CITAS (ID_CITA));

CREATE TABLE FOTOS(
ID_FOTO		NUMERIC(10)		PRIMARY KEY		IDENTITY(1,1),
URL_FOTO	VARCHAR(50)		NOT NULL,
ID_CITA		NUMERIC(5)		NOT NULL,
CONSTRAINT FK_FOTOS_CITA FOREIGN KEY(ID_CITA) REFERENCES CITAS(ID_CITA));

CREATE TABLE MENSAJES(
ID_MENSAJE		NUMERIC(10)		PRIMARY KEY		IDENTITY(1,1),
DESC_MENSAJE	VARCHAR(300)	NOT NULL,
FECHA_MENSAJE	DATETIME		NOT NULL,
ID_CITA		NUMERIC(5)		NOT NULL,
CONSTRAINT FK_MENSAJES_CITA FOREIGN KEY(ID_CITA) REFERENCES CITAS(ID_CITA));

CREATE TABLE REPUESTOS(
ID_REPUESTO		NUMERIC(10)		PRIMARY KEY		IDENTITY(1,1),
DESC_MENSAJE	VARCHAR(100)	NOT NULL);

CREATE TABLE SERVICIO_REPUESTO(
ID_SERVICIO_REPUESTO		NUMERIC(10)		PRIMARY KEY		IDENTITY(1,1),
CANTIDAD				NUMERIC(3)		NOT NULL,
VALOR_REPUESTO			NUMERIC(7)		NOT NULL,
ID_SERVICIO				NUMERIC(5)		NOT NULL,
ID_REPUESTO				NUMERIC(10)		NOT NULL,
CONSTRAINT FK_SERV_REP_SERV FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS (ID_SERVICIO),
CONSTRAINT FK_SERV_REP_REP FOREIGN KEY (ID_REPUESTO) REFERENCES REPUESTOS (ID_REPUESTO));